name: GitHubActionsBuilds

on:
  push:
    branches:
      - master

jobs:
  generate_version_number:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
    - name: Generate build number
      id: buildnumber
      uses: onyxmueller/build-tag-number@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  build_docker:
    needs: generate_version_number
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: devedse
        password: ${{ secrets.DOCKERHUBTOKEN }}

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Set Image Tags
      id: tags
      run: |
        VERSION=1.0.${{needs.generate_version_number.outputs.build_number}}
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

        if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
          echo "TAGS=-t devedse/devesweagents:${VERSION} -t devedse/devesweagents:latest" >> $GITHUB_ENV
        else
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
          echo "TAGS=-t devedse/devesweagents:${VERSION} -t devedse/devesweagents:beta_${BRANCH_NAME}" >> $GITHUB_ENV
        fi

    - name: Build and Push Docker Image
      run: |
        docker buildx build --platform linux/arm64,linux/amd64 \
          --build-arg BUILD_VERSION=${{ env.VERSION }} \
          ${{ env.TAGS }} \
          --push .